### ISSUE TITLE
Build/Deploy Pipeline OS Target

### ISSUE THREAD

**Issue by Applicant-SF** [Superformula/test-full-stack#12]
Is there a target OS for the build pipeline? E.g. Windows, Linux, Mac OS?

Or, should I try to make the build/deploy pipeline portable even if it means introducing further dependencies?

**Comment by julian-sf** [comment]
We don't have a specific build pipeline for this test, we leave that up to the candidate.  Generally, we like to see cloud-based solutions if possible.  Most of our developers work on Mac laptops and we have our CI pipelines build things in Linux (for the most part).  Since they are mostly *nix based this is usually not a problem with portability.
